export const SET_MATERIALS = 'SET_MATERIALS';
export const FETCH_BUILDING_MATERIAL_INVENTORY_TYPES = 'FETCH_BUILDING_MATERIAL_INVENTORY_TYPES'
export const POST_BUILDING_MATERIAL_INVENTORY_TYPE = 'POST_BUILDING_MATERIAL_INVENTORY_TYPE'

export default SET_MATERIALS;
