export const SET_MATERIALS = 'SET_MATERIALS';
export const FETCH_BUILDING_MATERIAL_INVENTORY_TYPES = 'FETCH_BUILDING_MATERIAL_INVENTORY_TYPES'
export const POST_BUILDING_MATERIAL_INVENTORY_TYPE = 'POST_BUILDING_MATERIAL_INVENTORY_TYPE'
export const RESET_POST_BUILDING_MATERIAL_INVENTORY_TYPE = 'RESET_POST_BUILDING_MATERIAL_INVENTORY_TYPE';

export const RESET_UPDATE_MATERIAL = 'RESET_UPDATE_MATERIAL';
export const POST_UPDATE_MATERIAL_START = 'POST_UPDATE_MATERIAL_START';
export const POST_UPDATE_MATERIAL_END = 'POST_UPDATE_MATERIAL_END';
export const POST_UPDATE_MATERIAL_ERROR = 'POST_UPDATE_MATERIAL_ERROR';

export const RESET_UPDATE_MATERIAL_BULK = 'RESET_UPDATE_MATERIAL_BULK';
export const POST_UPDATE_MATERIAL_START_BULK = 'POST_UPDATE_MATERIAL_START_BULK';
export const POST_UPDATE_MATERIAL_END_BULK = 'POST_UPDATE_MATERIAL_END_BULK';
export const POST_UPDATE_MATERIAL_ERROR_BULK = 'POST_UPDATE_MATERIAL_ERROR_BULK';

export default SET_MATERIALS;
